-- FACILITANDO A EXCLUSÃO E CRIAÇÃO DE AGENDAS
-- DOIS IDS ADICIONADOS. UM PARA CASO O USUÁRIO EXCLUA A AGENDA INTEIRA E OUTRO PARA CASO ELE EXCLUA APENAS O HORÁRIO NA TABELA.

-- 19/05/2017

ALTER TABLE ponto.tb_agenda_exames ADD COLUMN horario_id integer;



